//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDunk.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class AdminUser
    {
        [Display(Name = "User Name:")]
        [Required(ErrorMessage = "User Name không được trống")]
        public string Username { get; set; }
        [Display(Name = "Mat khau:")]
        [Required(ErrorMessage = "Password không được trống")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [NotMapped]
        [Display(Name = "Nhap lai mat khau:")]
        [Compare("Password", ErrorMessage = "Password bị sai")]
        public string PasswordConfirm { get; set; }
        public string Role { get; set; }
    }
}
