//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDunk.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
        [Display(Name = "Dien Thoai:")]
        [RegularExpression("^[0-9]{1,10}$", ErrorMessage = "Phone number chỉ được chứa các ký tự số và không vượt quá 10 ký tự")]
        [Required(ErrorMessage = "Số điện thoại không được trống")]
        public string CusPhone { get; set; }
        [Display(Name = "Mat khau:")]
        [Required(ErrorMessage = "Password không được trống")]
        [DataType(DataType.Password)]
        public string CusPassword { get; set; }
        [NotMapped]
        [Display(Name = "Nhap lai mat khau:")]
        [Compare("CusPassword", ErrorMessage = "Password bị sai")]

        public string PasswordConfirm { get; set; }
        [Display(Name = "User Name:")]
        [Required(ErrorMessage = "User Name không được trống")]
        public string CusName { get; set; }
        [Display(Name = "E-mail:")]
        [Required(ErrorMessage = "E-mail  không được trống")]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Định dạng email không hợp lệ")]
        [EmailAddress(ErrorMessage = "Invalid Email")]
        public string CusEmail { get; set; }
        [Display(Name = "Địa chỉ:")]
        public string Address { get; set; }
        [Display(Name = "Gioi tinh:")]
        public Nullable<bool> Gender { get; set; }
        [Display(Name = "Ngay sinh:")]
        [Required(ErrorMessage = "Date of birth không được trống")]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        [NotMapped]
        public string ErrorLogin { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
