//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDunk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProDetails = new HashSet<ProDetail>();
        }
    
        public int ProID { get; set; }
        public string ProName { get; set; }
        public int CatID { get; set; }
        public string ProImage { get; set; }
        public double Price { get; set; }
        public double DiscountPercent { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int IDRCam { get; set; }
        public int IDFCam { get; set; }
        public int IDScreen { get; set; }
        public int IDBatery { get; set; }
        public double PriceReduce { get { return Price - (Price * DiscountPercent / 100); } }
        public virtual Battery Battery { get; set; }
        public virtual Category Category { get; set; }
        public virtual FrontCamera FrontCamera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProDetail> ProDetails { get; set; }
        public virtual RearCamera RearCamera { get; set; }
        public virtual Screen Screen { get; set; }
    }
}
